"balance_type.invalid" = "Balance type invalid"
"coa.code.exists" = "COA Code already exists"
"coa.not.found" = "COA not found"
"coa.type.not.found" = "COA type not found"
"credential.invalid" = "User Credential Invalid"
"company.exists" = "Perusahaan sudah terdaftar"
"company.success.created" = "Sukses membuat data perusahaan"
"company.success.updated" = "Sukses mengupdate data perusahaan"
"company_structures.empty" = "Harus buat struktur perusahaan"
"company.success.fetch" = "Sukses mengambil data perusahaan"
"company.not.exists" = "Data Perusahaan tidak ditemukan"
"company.success.delete" = "Sukses menghapus data perusahaan"
"company.fetch.success" = "Sukses mengambil data perusahaan"
"email.already.exists" = "Email Already Exists"
"file.extension.forbidden" = "File format invalid"
"file.has.no.extension" = "File has not extension"
"file.too.large" = "File too large, max 2mb"
"get.type_offices" = "Sukses mengammbil tipe kantor"
"invalid.token" = "Invalid Token"
"parent.coa.not.found" = "Parent COA not found"
"menu.success" = "Sukses mengambil data menu"
"role.already.exists" = "Role already exists"
"role.forbidden.access" = "Role doesn't have access"
"role.not.found" = "Role Not Found"
"role.success" = "Sukses mengambil data Role"
"school.not.found" = "School Not Found"
"something.went.wrong" = "Oops ada kesalahan, Hubungi developer terkait isu ini"
"student.already.exists" = "Student already exists"
"success.get_coa" = "Success get data COA"
"type_office.created" = "Tipe kantor berhasil dibuat"
"user.not.found" = "User Not Found"
"user.success.delete" = "Sukses Menghapus User"
"username.already.exist" = "Username already exist"
"student.shift.not.exists" = "Shift murid tidak ditemukan"
"day.schooltierid.productid.required"="day, schoolTierId dan producId harus diisi"
"session" = "Data Sesi berhasil diambil"
"question_templates.exists" = "Template pertanyaan sudah terdaftar"
"project.stat.found" = "Statistik Projek ditemukan"
"inventory.not_found" = "Inventaris Tidak Ditemukan"