"balance_type.invalid" = "Balance type invalid"
"coa.code.exists" = "COA Code already exists"
"coa.not.found" = "COA not found"
"coa.type.not.found" = "COA type not found"
"credential.invalid" = "User Credential Invalid"
"company.exists" = "Company Already exists"
"company.success.created" = "Success Create Company Data"
"company.success.updated" = "Success Update Company Data"
"company_structures.empty" = "Company Structures must be set"
"company.success.fetch" = "Success get data companies"
"company.not.exists" = "Company not exists"
"company.success.delete" = "Company Success Delete"
"company.fetch.success" = "Success get detail company"
"email.already.exists" = "Email Already Exists"
"file.extension.forbidden" = "File format invalid"
"file.has.no.extension" = "File has not extension"
"file.too.large" = "File too large, max 2mb"
"get.type_offices" = "Success get type offices"
"invalid.token" = "Invalid Token"
"menu.success" = "Success Fetch data menu"
"parent.coa.not.found" = "Parent COA not found"
"role.already.exists" = "Role already exists"
"role.forbidden.access" = "Role doesn't have access"
"role.not.found" = "Role Not Found"
"role.success" = "Success insert/update New Role"
"role.delete" = "Success Delete Role"
"role.default" = "Forbidden to delete default role"
"school.not.found" = "School Not Found"
"something.went.wrong" = "Oops something went wrong, Contact Developer for the issue"
"student.already.exists" = "Student already exists"
"success.get_coa" = "Success get data COA"
"type_office.created" = "Type Office successfully created"
"user.not.found" = "User Not Found"
"user.success.delete" = "Success delete user"
"username.already.exist" = "Username already exist"
"student.shift.not.exists"="Student Shift Not Exist"
"day.schooltierid.productid.required"="day, schoolTierId and productId is required"
"session" = "Success Get Session"
"question_templates.exists" = "Question template already exists"
"project.stat.found" = "Project Stat Found"
"inventory.not_found" = "Inventory Not Found"